(load "Rental.clp")
(reset)
;; Room density extreme: 5 people, only 2 single rooms
(assert (user-responses
  (step create-profile)
  (num-people 5)
  (ages 28 27 26 25 24)
  (income 3500)
  (max_budget 1800)
  (budget_is_strict no)
  (owns-car no)
  (has-pets no)
  (works_any yes)
  (work_lats 10100)
  (work_longs 19900)
  (studies_any no)
  (study_lats)
  (study_longs)
))
(run)
(exit)
