(load "Rental.clp")
(reset)
;; Elderly couple; accessibility important, no work/study
(assert (user-responses
  (step create-profile)
  (num-people 2)
  (ages 72 70)
  (income 2400)
  (max_budget 1200)
  (budget_is_strict no)
  (owns-car no)
  (has-pets no)
  (works_any no)
  (studies_any no)
  (work_lats)
  (work_longs)
  (study_lats)
  (study_longs)
))
(run)
(exit)
