(load "Rental.clp")
(reset)
;; Couple young, no car, no pets, 2 workers at city center, no students
(assert (user-responses
	(step create-profile)
	(num-people 2)
	(ages 27 26)
	(income 2500)
	(max_budget 1200)
	(budget_is_strict no)
	(owns-car no)
	(has-pets no)
	(works_any yes)
	(work_lats 10000 10100)
	(work_longs 20000 19900)
	(studies_any no)
	(study_lats)
	(study_longs)
))
(run)
(exit)
