(load "Rental.clp")
(reset)
;; Pets & car preferences; 3 people, workers only
(assert (user-responses
  (step create-profile)
  (num-people 3)
  (ages 32 30 5)
  (income 3200)
  (max_budget 1500)
  (budget_is_strict no)
  (owns-car yes)
  (has-pets yes)
  (works_any yes)
  (work_lats 9900 10300)
  (work_longs 20200 19700)
  (studies_any no)
  (study_lats)
  (study_longs)
))
(run)
(exit)
