(load "Rental.clp")
(reset)
;; Edge case: very strict low budget, 2 people, no work/study
(assert (user-responses
  (step create-profile)
  (num-people 2)
  (ages 29 27)
  (income 1400)
  (max_budget 700)
  (budget_is_strict yes)
  (owns-car no)
  (has-pets no)
  (works_any no)
  (studies_any no)
  (work_lats)
  (work_longs)
  (study_lats)
  (study_longs)
))
(run)
(exit)
