(load "Rental.clp")
(reset)
;; Single elderly individual
(assert (user-responses
	(step create-profile)
	(num-people 1)
	(ages 70)
	(income 2200)
	(max_budget 1000)
	(budget_is_strict yes)
	(owns-car no)
	(has-pets no)
	(works_any no)
	(work_lats)
	(work_longs)
	(studies_any no)
	(study_lats)
	(study_longs)
))
(run)
(exit)
